# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target ‘ContraceptiveRisk’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ContraceptiveRisk
    pod 'Charts', '~> 3.0.1'
    pod 'CSVImporter', '~> 1.7'

  # target 'ContraceptiveRiskTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
